FROM nginx:latest
MAINTAINER Duy Le (duyleminh1402@gmail.com)

COPY nginx.conf /etc/nginx/
COPY sites-enabled/site.conf /etc/nginx/sites-enabled/site.conf
COPY sites-enabled/admin.conf /etc/nginx/sites-enabled/admin.conf